---
- name: Respaldar la configuración XML de pfSense (Solo última copia)
  hosts: pfsense
  gather_facts: false

  tasks:
    - name: Descargar el archivo config.xml desde pfSense
      ansible.builtin.fetch:
        src: /conf/config.xml
        dest: "/opt/pfsense_backups/pfsense_config_latest.xml"
        flat: true

    - name: Confirmar el guardado del respaldo
      ansible.builtin.debug:
        msg: "Copia de seguridad guardada con éxito en /opt/pfsense_backups/pfsense_config_latest.xml"
