---
- name: Actualizar Ubuntu Server (Host Docker)
  hosts: ubuntu_docker

  tasks:
    - name: Actualizar la lista de paquetes (apt update)
      ansible.builtin.shell: sudo apt-get update
      changed_when: false

    - name: Aplicar actualizaciones de paquetes (apt upgrade)
      ansible.builtin.shell: sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y

    - name: Verificar si el sistema requiere reinicio
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_file

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.shell: sudo reboot
      when: reboot_file.stat.exists

    - name: Esperar 15 segundos para dar tiempo al demonio de Docker
      ansible.builtin.pause:
        seconds: 15
      when: reboot_file.stat.exists

    - name: Verificar el estado de los contenedores Docker
      ansible.builtin.command: docker ps --format "{{ '{{' }}.Names{{ '}}' }} - {{ '{{' }}.Status{{ '}}' }}"
      register: docker_status
      changed_when: false

    - name: Mostrar contenedores activos tras el mantenimiento
      ansible.builtin.debug:
        var: docker_status.stdout_lines
      
